import test from 'node:test';import assert from 'node:assert/strict';
import {attendanceId,makeToken,hash,emailKey,normalizeEmail,validateToken,automaticStatus,schedule,safeCSV,safeUrl,driveEmbed,checkAttachment} from '../src/domain.js';
test('attendance ID deterministic and pair-order sensitive',()=>{assert.equal(attendanceId('m1','s1'),attendanceId('m1','s1'));assert.notEqual(attendanceId('a_b','c'),attendanceId('a','b_c'));assert.notEqual(attendanceId('m1','s1'),attendanceId('s1','m1'))});
test('QR tokens cryptographically generated and distinct',()=>{const t=new Set(Array.from({length:1000},makeToken));assert.equal(t.size,1000);for(const s of t)assert.match(s,/^[a-f0-9]{48}$/)});
test('email normalized and hashed deterministically',()=>{assert.equal(normalizeEmail(' A@Example.com '),'a@example.com');assert.equal(emailKey('A@example.com'),emailKey('a@example.com'));assert.throws(()=>normalizeEmail('bad'))});
const state={state:'open',opensAt:1000,closesAt:5000,activeTokenHash:'h',qrVersion:2};const token={version:2,expiresAt:3000,revokedAt:null};
test('valid token accepted',()=>assert.doesNotThrow(()=>validateToken({token,session:state,tokenHash:'h',now:2000})));
test('exact expiry is rejected',()=>assert.throws(()=>validateToken({token,session:state,tokenHash:'h',now:3000}),e=>e.code==='QR_INVALID_OR_EXPIRED'));
test('previous QR rejected after regeneration',()=>assert.throws(()=>validateToken({token,session:{...state,activeTokenHash:'new'},tokenHash:'h',now:2000})));
test('revoked QR rejected',()=>assert.throws(()=>validateToken({token:{...token,revokedAt:1500},session:state,tokenHash:'h',now:2000})));
test('QR wrong version rejected',()=>assert.throws(()=>validateToken({token:{...token,version:1},session:state,tokenHash:'h',now:2000})));
test('closed session rejected',()=>assert.throws(()=>validateToken({token,session:{...state,state:'closed'},tokenHash:'h',now:2000}),e=>e.code==='SESSION_CLOSED'));
test('before opening and at closing rejected',()=>{for(const n of [999,5000])assert.throws(()=>validateToken({token,session:state,tokenHash:'h',now:n}))});
test('late boundary inclusive for hadir',()=>{assert.equal(automaticStatus(2000,2000),'hadir');assert.equal(automaticStatus(2001,2000),'terlambat')});
test('invalid schedule rejected',()=>assert.throws(()=>schedule({startsAt:'bad'})));
test('HTTPS-only reference URLs',()=>{assert.equal(safeUrl('https://github.com'),'https://github.com/');assert.throws(()=>safeUrl('javascript:alert(1)'));assert.throws(()=>safeUrl('http://example.com'))});
test('Drive and Slides URLs become controlled embed URLs',()=>{assert.equal(driveEmbed('https:'+'//drive.google.com/file/d/AbCdEfGhIjKlMn/view?usp=sharing').driveEmbedUrl,'https:'+'//drive.google.com/file/d/AbCdEfGhIjKlMn/preview');assert.match(driveEmbed('https:'+'//docs.google.com/presentation/d/AbCdEfGhIjKlMn/edit').driveEmbedUrl,/\/embed\?/);assert.throws(()=>driveEmbed('https:'+'//example.com/file/d/AbCdEfGhIjKlMn'));assert.throws(()=>driveEmbed('https:'+'//drive.google.com/open?id=AbCdEfGhIjKlMn'))});
test('CSV escapes quotes and formula payloads',()=>{const csv=safeCSV([['=1+1','a"b','@SUM(A1)']]);assert.match(csv,/"'=1\+1"/);assert.match(csv,/a""b/);assert.match(csv,/"'@SUM/)});
test('attachment verifies signatures and size',()=>{assert.equal(checkAttachment('a.pdf',Buffer.from('%PDF-1.7')),'application/pdf');assert.equal(checkAttachment('a.txt',Buffer.from('hello')),'text/plain');assert.throws(()=>checkAttachment('a.pdf',Buffer.from('<html>')));assert.throws(()=>checkAttachment('a.exe',Buffer.from('MZ')));assert.throws(()=>checkAttachment('a.txt',Buffer.alloc(21*1024*1024,65)))});
