import express from 'express';
import {initializeApp, cert} from 'firebase-admin/app';
import {getAuth} from 'firebase-admin/auth';
import {getFirestore,Timestamp,FieldValue} from 'firebase-admin/firestore';
import {getStorage} from 'firebase-admin/storage';
import {onRequest} from 'firebase-functions/v2/https';
import {onSchedule} from 'firebase-functions/v2/scheduler';
import {AppError,fail,hash,emailKey,normalizeEmail,str,docId,makeToken,attendanceId,validateToken,automaticStatus,statuses,schedule,safeCSV,safeUrl,driveEmbed,checkAttachment} from './domain.js';
const storageBucket=process.env.STORAGE_BUCKET||(process.env.GCLOUD_PROJECT?`${process.env.GCLOUD_PROJECT}.firebasestorage.app`:undefined);
let adminConfig={storageBucket};
if(process.env.FIREBASE_SERVICE_ACCOUNT){
  try{
    const cred=JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT);
    adminConfig={credential:cert(cred),projectId:cred.project_id,storageBucket:cred.project_id?`${cred.project_id}.firebasestorage.app`:storageBucket};
  }catch(err){console.error('Error parsing FIREBASE_SERVICE_ACCOUNT:',err.message);}
}else if(process.env.GCLOUD_PROJECT){
  adminConfig.projectId=process.env.GCLOUD_PROJECT;
}
initializeApp(adminConfig);const db=getFirestore(),auth=getAuth(),bucket=getStorage().bucket(adminConfig.storageBucket||storageBucket);
const region='asia-southeast2';const now=()=>Timestamp.now();const app=express();app.disable('x-powered-by');
app.use((req,res,next)=>{res.set('Cache-Control','no-store');res.set('X-Content-Type-Options','nosniff');next()});
app.use(express.json({limit:'256kb'}));
app.get('/health',(req,res)=>res.json({status:'ok'}));
app.get('/',(req,res)=>res.json({status:'ok',service:'secure-api'}));
const route=fn=>(req,res,next)=>Promise.resolve(fn(req,res)).catch(next);
const ref=(c,id)=>db.collection(c).doc(docId(id));
const userRef=uid=>db.collection('users').doc(uid);
const classRef=id=>ref('classes',id);
const memberRef=(cid,uid)=>classRef(cid).collection('members').doc(uid);
const teacherRef=(cid,uid)=>classRef(cid).collection('teachers').doc(uid);
function wire(v){if(v instanceof Timestamp)return v.toDate().toISOString();if(Array.isArray(v))return v.map(wire);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,wire(x)]));return v}
const row=d=>({id:d.id,...wire(d.data())});
function publicSession(d){if(!d?.exists)return null;const {activeTokenHash,...data}=d.data();return {id:d.id,...wire(data)}}
function audit(tx,uid,action,entityType,entityId,classId,extra={}){tx.create(db.collection('auditLogs').doc(),{actorId:uid,action,entityType,entityId,classId:classId||null,createdAt:now(),...extra})}
const rateLimitMap=new Map();
function limit(uid,action,max=60){const minute=Math.floor(Date.now()/60000);const key=`${uid}:${action}:${minute}`;const count=(rateLimitMap.get(key)||0)+1;fail(count<=max,'RATE_LIMITED','Terlalu banyak permintaan. Coba lagi satu menit lagi.',429);rateLimitMap.set(key,count);if(rateLimitMap.size>2000){const currentMin=Math.floor(Date.now()/60000);for(const [k] of rateLimitMap){const parts=k.split(':');if(Number(parts[parts.length-1])<currentMin-2)rateLimitMap.delete(k);}}}
const allowedCache=new Map();
const userCache=new Map();
function invalidateUserCache(uid,email){if(uid)userCache.delete(uid);if(email)allowedCache.delete(emailKey(email));}
async function allowed(email){const k=emailKey(email);const cached=allowedCache.get(k);const t=Date.now();if(cached&&cached.expire>t){fail(cached.allowed,'EMAIL_NOT_ALLOWED','Email belum diizinkan. Hubungi admin.',403);return}const d=await db.collection('allowedEmails').doc(k).get();const isAllowed=d.exists&&d.data().active===true;allowedCache.set(k,{allowed:isAllowed,expire:t+60000});fail(isAllowed,'EMAIL_NOT_ALLOWED','Email belum diizinkan. Hubungi admin.',403);}
async function getCachedUser(uid){const t=Date.now();const cached=userCache.get(uid);if(cached&&cached.expire>t)return cached.data;const u=await userRef(uid).get();if(u.exists){userCache.set(uid,{data:u.data(),expire:t+45000});return u.data()}return null;}
app.use('/api',async(req,res,next)=>{try{const token=/^Bearer (.+)$/.exec(req.headers.authorization||'')?.[1];fail(token,'UNAUTHENTICATED','Silakan masuk.',401);let decoded;try{decoded=await auth.verifyIdToken(token)}catch{throw new AppError('UNAUTHENTICATED','Sesi tidak valid. Silakan masuk kembali.',401)}
 fail(decoded.email,'EMAIL_REQUIRED','Akun harus mempunyai email.',403);fail(decoded.email_verified===true||decoded.email.endsWith('@secure.sch.id')||process.env.FUNCTIONS_EMULATOR==='true','VERIFY_EMAIL','Verifikasi email dahulu, kemudian masuk kembali.',403);req.uid=decoded.uid;req.email=normalizeEmail(decoded.email);limit(req.uid,'requests',240);await allowed(req.email);
 let userData=await getCachedUser(req.uid);if(!userData){await db.runTransaction(async tx=>{const current=await tx.get(userRef(req.uid));if(!current.exists)tx.create(userRef(req.uid),{email:req.email,displayName:decoded.name||req.email.split('@')[0],roles:['siswa'],active:true,createdAt:now(),updatedAt:now()})});userData=(await userRef(req.uid).get()).data();userCache.set(req.uid,{data:userData,expire:Date.now()+45000});}
 fail(userData.active===true,'ACCOUNT_DISABLED','Akun dinonaktifkan.',403);req.user=userData;next();}catch(e){next(e)}});
function role(req,r){fail(req.user.roles?.includes(r),'FORBIDDEN','Anda tidak mempunyai akses.',403)}
async function classAccess(req,cid,{teacher=false}={}){const c=await classRef(cid).get();fail(c.exists&&!c.data().archivedAt,'CLASS_UNAVAILABLE','Kelas tidak tersedia.',404);const [t,m]=await Promise.all([teacherRef(cid,req.uid).get(),memberRef(cid,req.uid).get()]);const isTeacher=req.user.roles?.includes('pengajar')&&t.exists&&t.data().active===true;const isMember=req.user.roles?.includes('siswa')&&m.exists&&m.data().active===true;fail(teacher?isTeacher:(isTeacher||isMember),'FORBIDDEN','Bukan anggota atau pengajar kelas ini.',403);return {...c.data(),id:cid,isTeacher};}
async function teacherTx(tx,uid,cid){const [u,c,t]=await Promise.all([tx.get(userRef(uid)),tx.get(classRef(cid)),tx.get(teacherRef(cid,uid))]);fail(u.exists&&u.data().active&&u.data().roles?.includes('pengajar')&&c.exists&&!c.data().archivedAt&&t.exists&&t.data().active,'FORBIDDEN','Penugasan pengajar tidak aktif.',403);return c.data()}
app.get('/api/me',route(async(req,res)=>{const p=await db.collection('profiles').doc(req.uid).get();res.json({uid:req.uid,...wire(req.user),profile:p.exists?wire(p.data()):{}})}));
app.patch('/api/me',route(async(req,res)=>{const bio=str(req.body.bio??'','Bio',200,false),githubUrl=safeUrl(str(req.body.githubUrl??'','GitHub',300,false));if(githubUrl)fail(new URL(githubUrl).hostname==='github.com','INVALID_URL','Gunakan URL profil github.com.');await db.collection('profiles').doc(req.uid).set({bio,githubUrl,updatedAt:now()},{merge:true});res.json({ok:true})}));
app.post('/api/logout-all',route(async(req,res)=>{await auth.revokeRefreshTokens(req.uid);res.json({ok:true})}));
app.post('/api/admin/emails',route(async(req,res)=>{role(req,'admin');await limit(req.uid,'addEmail',20);const email=normalizeEmail(req.body.email),r=db.collection('allowedEmails').doc(emailKey(email));await db.runTransaction(async tx=>{const d=await tx.get(r);fail(!d.exists,'EMAIL_EXISTS','Email sudah terdaftar.',409);tx.create(r,{email,active:true,addedBy:req.uid,createdAt:now()});audit(tx,req.uid,'allow_email','allowedEmails',r.id,null)});invalidateUserCache(null,email);res.status(201).json({email})}));
function resolveEmail(input){let s=String(input||'').trim().toLowerCase();if(!s.includes('@'))s=`${s}@secure.sch.id`;return normalizeEmail(s)}
app.post('/api/admin/users',route(async(req,res)=>{role(req,'admin');await limit(req.uid,'addUser',60);const rawId=str(req.body.username||req.body.email,'Username/Email',100);const email=resolveEmail(rawId);const name=str(req.body.name||rawId.split('@')[0],'Nama',100);const chosenRole=req.body.role==='pengajar'?'pengajar':'siswa';const initialPassword=req.body.password?str(req.body.password,'Password',100):'Secure123!';fail(initialPassword.length>=6,'PASSWORD_SHORT','Password minimal 6 karakter.');let u;try{u=await auth.getUserByEmail(email);await auth.updateUser(u.uid,{displayName:name,emailVerified:true,...(req.body.password?{password:initialPassword}:{})});}catch(e){if(e.code!=='auth/user-not-found')throw e;u=await auth.createUser({email,displayName:name,password:initialPassword,emailVerified:true});}await db.collection('allowedEmails').doc(emailKey(email)).set({email,active:true,addedBy:req.uid,createdAt:now()},{merge:true});const ur=userRef(u.uid);await db.runTransaction(async tx=>{tx.set(ur,{email,displayName:name,roles:[chosenRole],active:true,updatedAt:now(),createdAt:now()},{merge:true});audit(tx,req.uid,'create_user','users',u.uid,null,{role:chosenRole,email})});invalidateUserCache(u.uid,email);let resetLink=null;try{resetLink=await auth.generatePasswordResetLink(email)}catch(err){console.error('generatePasswordResetLink error:',err.message)}res.status(201).json({uid:u.uid,email,username:email.split('@')[0],name,role:chosenRole,initialPassword,resetLink})}));
app.get('/api/admin/users',route(async(req,res)=>{role(req,'admin');const qs=await db.collection('users').limit(150).get();const users=qs.docs.map(row).sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''));res.json(users)}));
app.post('/api/admin/reset-link',route(async(req,res)=>{role(req,'admin');const rawId=str(req.body.username||req.body.email,'Username/Email',100);const email=resolveEmail(rawId);const link=await auth.generatePasswordResetLink(email);res.json({email,username:email.split('@')[0],link})}));
app.post('/api/admin/set-password',route(async(req,res)=>{role(req,'admin');const rawId=str(req.body.username||req.body.email,'Username/Email',100);const email=resolveEmail(rawId);const newPassword=str(req.body.password,'Password',100);fail(newPassword.length>=6,'PASSWORD_SHORT','Password minimal 6 karakter.');const u=await auth.getUserByEmail(email);await auth.updateUser(u.uid,{password:newPassword,emailVerified:true});await auth.revokeRefreshTokens(u.uid);invalidateUserCache(u.uid,email);res.json({ok:true,email,username:email.split('@')[0]})}));
app.post('/api/admin/toggle-user',route(async(req,res)=>{role(req,'admin');const uid=docId(req.body.uid);fail(uid!==req.uid,'CANNOT_DISABLE_SELF','Tidak dapat menonaktifkan akun sendiri.',400);const d=await userRef(uid).get();fail(d.exists,'NOT_FOUND','Pengguna tidak ditemukan.',404);const newActive=!d.data().active;await userRef(uid).update({active:newActive,updatedAt:now()});await auth.updateUser(uid,{disabled:!newActive});if(!newActive)await auth.revokeRefreshTokens(uid);invalidateUserCache(uid,d.data().email);res.json({ok:true,active:newActive})}));
app.post('/api/admin/change-role',route(async(req,res)=>{role(req,'admin');const uid=docId(req.body.uid);fail(uid!==req.uid,'CANNOT_CHANGE_SELF','Tidak dapat mengubah role akun sendiri.',400);const targetRole=req.body.role==='pengajar'?'pengajar':'siswa';const ur=userRef(uid);const us=await ur.get();fail(us.exists,'NOT_FOUND','Pengguna tidak ditemukan.',404);const batch=db.batch();batch.update(ur,{roles:[targetRole],updatedAt:now()});audit(batch,req.uid,'change_role','users',uid,null,{newRole:targetRole});await batch.commit();invalidateUserCache(uid,us.data().email);res.json({ok:true,role:targetRole})}));
const userClassesCache=new Map();
function invalidateClassCache(){userClassesCache.clear();}
app.get('/api/admin/classes',route(async(req,res)=>{role(req,'admin');const qs=await db.collection('classes').limit(100).get();const classes=await Promise.all(qs.docs.map(async d=>{const [tSnap,mSnap]=await Promise.all([d.ref.collection('teachers').where('active','==',true).get(),d.ref.collection('members').where('active','==',true).get()]);return {...row(d),teacherCount:tSnap.size,studentCount:mSnap.size}}));res.json(classes)}));
app.post('/api/admin/classes',route(async(req,res)=>{role(req,'admin');fail(req.body.name&&req.body.period,'INPUT','Nama kelas dan periode wajib diisi.');const rawId=req.body.id||req.body.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const id=docId(rawId);const r=classRef(id);await db.runTransaction(async tx=>{const d=await tx.get(r);fail(!d.exists,'EXISTS','ID Kelas sudah ada.',409);tx.create(r,{name:str(req.body.name,'Nama kelas',120),description:str(req.body.description||'Ekstrakurikuler coding SECURE','Deskripsi',500,false),period:str(req.body.period,'Periode',60),timezone:'Asia/Jakarta',membershipVersion:0,archivedAt:null,createdAt:now()});audit(tx,req.uid,'create_class','classes',id,id)});invalidateClassCache();res.status(201).json({id})}));
app.get('/api/admin/classes/:cid',route(async(req,res)=>{role(req,'admin');const cid=docId(req.params.cid);const c=await classRef(cid).get();fail(c.exists,'NOT_FOUND','Kelas tidak ditemukan.',404);const [tSnap,mSnap]=await Promise.all([classRef(cid).collection('teachers').get(),classRef(cid).collection('members').get()]);const teachers=await Promise.all(tSnap.docs.map(async d=>{const u=await getCachedUser(d.id);return {id:d.id,...wire(d.data()),displayName:u?.displayName||'—',email:u?.email||'—'}}));const members=await Promise.all(mSnap.docs.map(async d=>{const u=await getCachedUser(d.id);return {id:d.id,...wire(d.data()),displayName:d.data().displayName||(u?.displayName||'—'),email:u?.email||'—'}}));res.json({class:row(c),teachers,members})}));
app.post('/api/admin/classes/:cid/assign-teacher',route(async(req,res)=>{role(req,'admin');const cid=docId(req.params.cid);const rawId=req.body.teacherId||req.body.username||req.body.email;fail(rawId,'INPUT','Pilih pengajar.');let uid=rawId;if(rawId.includes('@')||!/^[a-zA-Z0-9_-]{20,}$/.test(rawId)){const email=resolveEmail(rawId);const u=await auth.getUserByEmail(email);uid=u.uid}const c=classRef(cid),ur=userRef(uid),tr=teacherRef(cid,uid);await db.runTransaction(async tx=>{const [cs,us]=await Promise.all([tx.get(c),tx.get(ur)]);fail(cs.exists,'NOT_FOUND','Kelas tidak ditemukan.',404);fail(us.exists&&us.data().roles?.includes('pengajar'),'ROLE','Pengguna bukan berstatus pengajar.',400);tx.set(tr,{teacherId:uid,active:true,assignedAt:now()},{merge:true});tx.update(c,{membershipVersion:(cs.data().membershipVersion||0)+1});audit(tx,req.uid,'assign_teacher','classes',uid,cid)});invalidateClassCache();res.json({ok:true})}));
app.post('/api/admin/classes/:cid/remove-teacher',route(async(req,res)=>{role(req,'admin');const cid=docId(req.params.cid),teacherId=docId(req.body.teacherId);const c=classRef(cid),tr=teacherRef(cid,teacherId);await db.runTransaction(async tx=>{const cs=await tx.get(c);fail(cs.exists,'NOT_FOUND','Kelas tidak ditemukan.',404);tx.update(tr,{active:false,removedAt:now()});tx.update(c,{membershipVersion:(cs.data().membershipVersion||0)+1});audit(tx,req.uid,'remove_teacher','classes',teacherId,cid)});invalidateClassCache();res.json({ok:true})}));
app.post('/api/admin/classes/:cid/enroll',route(async(req,res)=>{role(req,'admin');const cid=docId(req.params.cid);const rawId=req.body.studentId||req.body.username||req.body.email;fail(rawId,'INPUT','Pilih siswa.');let uid=rawId;if(rawId.includes('@')||!/^[a-zA-Z0-9_-]{20,}$/.test(rawId)){const email=resolveEmail(rawId);const u=await auth.getUserByEmail(email);uid=u.uid}const schoolClass=str(req.body.schoolClass||'','Kelas Sekolah',40,false);const c=classRef(cid),ur=userRef(uid),mr=memberRef(cid,uid);await db.runTransaction(async tx=>{const [cs,us,old]=await Promise.all([tx.get(c),tx.get(ur),tx.get(mr)]);fail(cs.exists,'NOT_FOUND','Kelas tidak ditemukan.',404);fail(us.exists&&us.data().roles?.includes('siswa'),'ROLE','Pengguna bukan berstatus siswa.',400);tx.set(mr,{studentId:uid,displayName:us.data().displayName||us.data().email.split('@')[0],schoolClass:schoolClass||old.data()?.schoolClass||'',active:true,joinedAt:old.data()?.joinedAt||now(),endedAt:null},{merge:true});tx.update(c,{membershipVersion:(cs.data().membershipVersion||0)+1});audit(tx,req.uid,'enroll_student','classes',uid,cid)});invalidateClassCache();res.json({ok:true})}));
app.post('/api/admin/classes/:cid/unenroll',route(async(req,res)=>{role(req,'admin');const cid=docId(req.params.cid),studentId=docId(req.body.studentId);const c=classRef(cid),mr=memberRef(cid,studentId);await db.runTransaction(async tx=>{const cs=await tx.get(c);fail(cs.exists,'NOT_FOUND','Kelas tidak ditemukan.',404);tx.update(mr,{active:false,endedAt:now()});tx.update(c,{membershipVersion:(cs.data().membershipVersion||0)+1});audit(tx,req.uid,'unenroll_student','classes',studentId,cid)});invalidateClassCache();res.json({ok:true})}));
app.post('/api/admin/classes/:cid/archive',route(async(req,res)=>{role(req,'admin');const cid=docId(req.params.cid),archive=req.body.archive!==false;await classRef(cid).update({archivedAt:archive?now():null});invalidateClassCache();res.json({ok:true,archived:archive})}));
app.delete('/api/admin/classes/:cid',route(async(req,res)=>{role(req,'admin');const cid=docId(req.params.cid);const c=classRef(cid);const cs=await c.get();fail(cs.exists,'NOT_FOUND','Kelas tidak ditemukan.',404);const [tSnap,mSnap,matSnap,meetSnap]=await Promise.all([c.collection('teachers').get(),c.collection('members').get(),db.collection('materials').where('classId','==',cid).get(),db.collection('meetings').where('classId','==',cid).get()]);const batch=db.batch();tSnap.docs.forEach(d=>batch.delete(d.ref));mSnap.docs.forEach(d=>batch.delete(d.ref));matSnap.docs.forEach(d=>batch.delete(d.ref));meetSnap.docs.forEach(d=>batch.delete(d.ref));batch.delete(c);audit(batch,req.uid,'delete_class','classes',cid,cid);await batch.commit();invalidateClassCache();res.json({ok:true})}));
app.patch('/api/admin/classes/:cid',route(async(req,res)=>{role(req,'admin');const cid=docId(req.params.cid);const c=classRef(cid);const cs=await c.get();fail(cs.exists,'NOT_FOUND','Kelas tidak ditemukan.',404);const up={};if(req.body.name!==undefined)up.name=str(req.body.name,'Nama kelas',120);if(req.body.description!==undefined)up.description=str(req.body.description,'Deskripsi',500,false);if(req.body.period!==undefined)up.period=str(req.body.period,'Periode',60);fail(Object.keys(up).length>0,'INPUT','Tidak ada data yang diubah.');up.updatedAt=now();const batch=db.batch();batch.update(c,up);audit(batch,req.uid,'update_class','classes',cid,cid);await batch.commit();invalidateClassCache();res.json({ok:true})}));
app.get('/api/classes',route(async(req,res)=>{const cached=userClassesCache.get(req.uid);const t=Date.now();if(cached&&cached.expire>t)return res.json(cached.data);const qs=await db.collection('classes').limit(101).get();fail(qs.size<=100,'LIMIT_REACHED','Batas instalasi 100 kelas. Tambahkan pagination kelas sebelum memperbesar skala.',409);const data=await Promise.all(qs.docs.filter(d=>!d.data().archivedAt).map(async d=>{let [m,t]=await Promise.all([memberRef(d.id,req.uid).get(),teacherRef(d.id,req.uid).get()]);const isTeacher=req.user.roles?.includes('pengajar')&&t.exists&&t.data().active;const isStudent=req.user.roles?.includes('siswa')&&m.exists&&m.data().active;return isTeacher||isStudent?{...row(d),isTeacher:!!isTeacher}:null}));const resData=data.filter(Boolean);userClassesCache.set(req.uid,{data:resData,expire:t+30000});res.json(resData)}));
const cursorLimit=req=>Math.min(50,Math.max(1,Number(req.query.limit)||25));
async function paginate(q,req,col){if(req.query.cursor){const c=await ref(col,req.query.cursor).get();fail(c.exists,'INVALID_CURSOR','Cursor tidak valid.');q=q.startAfter(c)}const n=cursorLimit(req),s=await q.limit(n+1).get();return {data:s.docs.slice(0,n).map(row),nextCursor:s.size>n?s.docs[n-1].id:null}}
app.get('/api/classes/:cid/materials',route(async(req,res)=>{const c=await classAccess(req,req.params.cid);let q=db.collection('materials').where('classId','==',c.id);if(!c.isTeacher)q=q.where('status','==','published');res.json(await paginate(q.orderBy('updatedAt','desc'),req,'materials'))}));
async function materialAccess(req,id,teacher=false){const m=await ref('materials',id).get();fail(m.exists,'NOT_FOUND','Materi tidak ditemukan.',404);const c=await classAccess(req,m.data().classId,{teacher});fail(c.isTeacher||m.data().status==='published','FORBIDDEN','Materi belum diterbitkan.',403);return {m,c}}
app.get('/api/materials/:id',route(async(req,res)=>{const {m}=await materialAccess(req,req.params.id);const attachments=await m.ref.collection('attachments').get();res.json({...row(m),attachments:attachments.docs.map(row)})}));
function materialInput(b){const status=b.status||'draft';fail(['draft','published','archived'].includes(status),'INVALID_STATUS','Status materi tidak valid.');const drive=driveEmbed(str(b.driveUrl??'','Embed Drive',1000,false));return {title:str(b.title,'Judul',120),summary:str(b.summary??'','Ringkasan',300,false),body:str(b.body,'Isi',100000),topic:str(b.topic??'Umum','Topik',60),link:safeUrl(str(b.link??'','Tautan',1000,false)),...drive,status,updatedAt:now()}}
app.post('/api/classes/:cid/materials',route(async(req,res)=>{const cid=docId(req.params.cid);const data=materialInput(req.body),m=db.collection('materials').doc();await db.runTransaction(async tx=>{await teacherTx(tx,req.uid,cid);tx.create(m,{...data,classId:cid,authorId:req.uid,createdAt:now(),publishedAt:data.status==='published'?now():null});audit(tx,req.uid,'create_material','materials',m.id,cid)});res.status(201).json({id:m.id})}));
app.patch('/api/materials/:id',route(async(req,res)=>{const mref=ref('materials',req.params.id),data=materialInput(req.body);await db.runTransaction(async tx=>{const m=await tx.get(mref);fail(m.exists,'NOT_FOUND','Materi tidak ditemukan.',404);await teacherTx(tx,req.uid,m.data().classId);tx.update(mref,{...data,publishedAt:data.status==='published'?(m.data().publishedAt||now()):m.data().publishedAt||null});audit(tx,req.uid,'update_material','materials',m.id,m.data().classId,{oldValue:{status:m.data().status},newValue:{status:data.status}})});res.json({ok:true})}));
app.post('/api/materials/:id/attachments',express.raw({type:'application/octet-stream',limit:'20mb'}),route(async(req,res)=>{await limit(req.uid,'upload',10);const {m}=await materialAccess(req,req.params.id,true),name=str(req.query.name,'Nama file',160),type=checkAttachment(name,req.body),a=m.ref.collection('attachments').doc(),path=`class-materials/${m.data().classId}/${m.id}/${a.id}`;await bucket.file(path).save(req.body,{resumable:false,metadata:{contentType:type,cacheControl:'private, no-store'}});try{await a.create({storagePath:path,originalName:name,contentType:type,size:req.body.length,createdAt:now()})}catch(e){await bucket.file(path).delete({ignoreNotFound:true});throw e}res.status(201).json({id:a.id})}));
app.get('/api/materials/:id/attachments/:aid',route(async(req,res)=>{const {m}=await materialAccess(req,req.params.id);const a=await m.ref.collection('attachments').doc(docId(req.params.aid)).get();fail(a.exists,'NOT_FOUND','Lampiran tidak ditemukan.',404);res.set('Content-Type',a.data().contentType);res.set('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(a.data().originalName)}`);bucket.file(a.data().storagePath).createReadStream().on('error',()=>{if(!res.headersSent)res.status(404).end();else res.destroy()}).pipe(res)}));
app.get('/api/classes/:cid/meetings',route(async(req,res)=>{await classAccess(req,req.params.cid);const result=await paginate(db.collection('meetings').where('classId','==',req.params.cid).orderBy('startsAt','desc'),req,'meetings');if(result.data.length){const sSnaps=await Promise.all(result.data.map(m=>ref('attendanceSessions',m.id).get()));result.data=result.data.map((m,idx)=>({...m,session:publicSession(sSnaps[idx])}));}res.json(result)}));
function materialIdsInput(value){const ids=Array.isArray(value)?value:[];fail(ids.length<=30,'LIMIT_REACHED','Maksimal 30 materi per pertemuan.');return [...new Set(ids.map(docId))]}
function meetingInput(b){const times=schedule(b),data={title:str(b.title,'Judul',120),location:str(b.location??'','Lokasi',120,false),materialIds:materialIdsInput(b.materialIds)};for(const [k,v] of Object.entries(times))data[k]=Timestamp.fromMillis(v);return data}
async function validateMeetingMaterials(tx,cid,ids){const docs=await Promise.all(ids.map(id=>tx.get(ref('materials',id))));for(const d of docs)fail(d.exists&&d.data().classId===cid,'INVALID_MATERIAL','Semua materi harus berasal dari kelas yang sama.');}
async function meetingDetail(req,mid){const m=await ref('meetings',mid).get();fail(m.exists,'NOT_FOUND','Pertemuan tidak ditemukan.',404);const c=await classAccess(req,m.data().classId);const docs=await Promise.all((m.data().materialIds||[]).map(id=>ref('materials',id).get()));const materials=docs.filter(d=>d.exists&&(c.isTeacher||d.data().status==='published')).map(row);return {meeting:row(m),session:publicSession(await ref('attendanceSessions',mid).get()),materials}}
app.post('/api/classes/:cid/meetings',route(async(req,res)=>{const cid=docId(req.params.cid),data=meetingInput(req.body),r=db.collection('meetings').doc();await db.runTransaction(async tx=>{await teacherTx(tx,req.uid,cid);await validateMeetingMaterials(tx,cid,data.materialIds);tx.create(r,{...data,classId:cid,createdBy:req.uid,createdAt:now(),updatedAt:now()});audit(tx,req.uid,'create_meeting','meetings',r.id,cid)});res.status(201).json({id:r.id})}));
app.get('/api/meetings/:id',route(async(req,res)=>res.json(await meetingDetail(req,docId(req.params.id)))));
app.patch('/api/meetings/:id',route(async(req,res)=>{const mid=docId(req.params.id),mref=ref('meetings',mid),data=meetingInput(req.body);await db.runTransaction(async tx=>{const m=await tx.get(mref);fail(m.exists,'NOT_FOUND','Pertemuan tidak ditemukan.',404);await teacherTx(tx,req.uid,m.data().classId);const session=await tx.get(ref('attendanceSessions',mid));await validateMeetingMaterials(tx,m.data().classId,data.materialIds);tx.update(mref,{...data,updatedAt:now()});audit(tx,req.uid,'update_meeting','meetings',mid,m.data().classId,{oldValue:{title:m.data().title,materialIds:m.data().materialIds||[]},newValue:{title:data.title,materialIds:data.materialIds}})});res.json({ok:true})}));
app.post('/api/meetings/:id/open',route(async(req,res)=>{const mid=docId(req.params.id),sref=ref('attendanceSessions',mid),mref=ref('meetings',mid);await db.runTransaction(async tx=>{const [m,s]=await Promise.all([tx.get(mref),tx.get(sref)]);fail(m.exists,'NOT_FOUND','Pertemuan tidak ditemukan.',404);await teacherTx(tx,req.uid,m.data().classId);if(s.exists){fail(s.data().state==='open','SESSION_CLOSED','Sesi sudah ditutup dan tidak dapat dibuka ulang.',409);return}const members=await tx.get(classRef(m.data().classId).collection('members').where('active','==',true).limit(201));fail(members.size<=200,'LIMIT_REACHED','Maksimal 200 peserta per pertemuan pada versi ini.');fail(members.size>0,'EMPTY_CLASS','Kelas belum mempunyai peserta.');for(const d of members.docs)tx.create(mref.collection('participants').doc(d.id),{studentId:d.id,displayName:d.data().displayName||d.id,schoolClass:d.data().schoolClass||'',enrolledAtSnapshot:now()});const opensAtVal=now(),closesAtVal=m.data().closesAt||Timestamp.fromMillis(Date.now()+86400000),lateAfterVal=m.data().lateAfter||m.data().endsAt||opensAtVal;tx.create(sref,{classId:m.data().classId,state:'open',opensAt:opensAtVal,closesAt:closesAtVal,lateAfter:lateAfterVal,activeTokenHash:null,qrVersion:0,participantCount:members.size,rosterReady:true,finalizedAt:null,openedAt:opensAtVal});audit(tx,req.uid,'open_attendance','attendanceSessions',mid,m.data().classId)});res.json({ok:true})}));
app.post('/api/meetings/:id/qr',route(async(req,res)=>{await limit(req.uid,'generateQR',30);const mid=docId(req.params.id),token=makeToken(),tokenHash=hash(token),ttl=Number(req.body.ttl??60);fail(Number.isInteger(ttl)&&ttl>=30&&ttl<=300,'INVALID_TTL','TTL harus 30–300 detik.');const result=await db.runTransaction(async tx=>{const s=await tx.get(ref('attendanceSessions',mid));fail(s.exists,'SESSION_CLOSED','Buka sesi terlebih dahulu.',409);await teacherTx(tx,req.uid,s.data().classId);const old=s.data().activeTokenHash?await tx.get(db.collection('qrTokens').doc(s.data().activeTokenHash)):null;const time=Date.now();fail(s.data().state==='open'&&s.data().rosterReady,'SESSION_CLOSED','Sesi belum dibuka atau sudah ditutup.',409);const expiresAt=Timestamp.fromMillis(time+ttl*1000),version=s.data().qrVersion+1;if(old?.exists)tx.update(old.ref,{revokedAt:now()});tx.create(db.collection('qrTokens').doc(tokenHash),{meetingId:mid,classId:s.data().classId,version,generatedBy:req.uid,createdAt:now(),expiresAt,revokedAt:null,purgeAt:Timestamp.fromMillis(time+7*86400000)});tx.update(s.ref,{activeTokenHash:tokenHash,qrVersion:version});audit(tx,req.uid,'generate_qr','attendanceSessions',mid,s.data().classId,{newValue:{version}});return {expiresAt:expiresAt.toDate().toISOString(),version,serverTime:new Date(time).toISOString()}});res.json({payload:`SECURE:1:${token}`,...result})}));
app.post('/api/attendance/check-in',route(async(req,res)=>{role(req,'siswa');await limit(req.uid,'checkIn',20);const payload=str(req.body.payload,'QR',100);const match=/^SECURE:1:([a-f0-9]{48})$/.exec(payload);fail(match,'QR_INVALID_OR_EXPIRED','QR bukan kode SECURE yang valid.');const tokenHash=hash(match[1]);const result=await db.runTransaction(async tx=>{const token=await tx.get(db.collection('qrTokens').doc(tokenHash));fail(token.exists,'QR_INVALID_OR_EXPIRED','QR tidak dikenal atau sudah dibersihkan.',409);const t=token.data(),mid=t.meetingId,cid=t.classId;const refs=[ref('attendanceSessions',mid),ref('meetings',mid),userRef(req.uid),classRef(cid),memberRef(cid,req.uid),ref('meetings',mid).collection('participants').doc(req.uid),ref('attendance',attendanceId(mid,req.uid))];const [s,m,u,c,member,part,existing]=await Promise.all(refs.map(r=>tx.get(r)));fail(u.exists&&u.data().active&&u.data().roles?.includes('siswa')&&c.exists&&!c.data().archivedAt&&member.exists&&member.data().active&&part.exists,'NOT_ELIGIBLE','Anda bukan peserta aktif pertemuan ini.',403);fail(m.exists&&m.data().classId===cid,'NOT_FOUND','Pertemuan tidak valid.',404);if(existing.exists)return {code:'ALREADY_RECORDED',record:row(existing)};const time=Date.now();validateToken({token:t,session:s.exists?s.data():null,tokenHash,now:time});const data={meetingId:mid,classId:cid,studentId:req.uid,displayName:part.data().displayName,schoolClass:part.data().schoolClass,meetingTitle:m.data().title,meetingStartsAt:m.data().startsAt,status:automaticStatus(time,s.data().lateAfter),checkedInAt:Timestamp.fromMillis(time),source:'qr',qrVersion:t.version,recordedBy:req.uid,updatedAt:now()};tx.create(refs[6],data);return {code:'SUCCESS',record:{id:refs[6].id,...wire(data)}}});res.json(result)}));
async function close(mid,actor=null){const sref=ref('attendanceSessions',mid);await db.runTransaction(async tx=>{const s=await tx.get(sref);fail(s.exists,'NOT_FOUND','Sesi tidak ditemukan.',404);if(actor)await teacherTx(tx,actor,s.data().classId);else if(s.data().closesAt.toMillis()>Date.now())return;if(s.data().state==='closed')return;const t=s.data().activeTokenHash?await tx.get(db.collection('qrTokens').doc(s.data().activeTokenHash)):null;if(t?.exists)tx.update(t.ref,{revokedAt:now()});tx.update(sref,{state:'closed',activeTokenHash:null,closedAt:now()});audit(tx,actor||'system','close_attendance','attendanceSessions',mid,s.data().classId)});}
async function finalize(mid){const mref=ref('meetings',mid),sref=ref('attendanceSessions',mid);const [m,s,parts]=await Promise.all([mref.get(),sref.get(),mref.collection('participants').get()]);if(!m.exists||!s.exists||s.data().state!=='closed'||s.data().finalizedAt)return;for(let i=0;i<parts.size;i+=10){await Promise.all(parts.docs.slice(i,i+10).map(p=>db.runTransaction(async tx=>{const r=ref('attendance',attendanceId(mid,p.id)),a=await tx.get(r);if(!a.exists)tx.create(r,{meetingId:mid,classId:m.data().classId,studentId:p.id,displayName:p.data().displayName,schoolClass:p.data().schoolClass,meetingTitle:m.data().title,meetingStartsAt:m.data().startsAt,status:'tidak_hadir',checkedInAt:null,source:'system',qrVersion:null,recordedBy:'system',updatedAt:now()})})));}await sref.update({finalizedAt:now()});}
app.post('/api/meetings/:id/close',route(async(req,res)=>{const mid=docId(req.params.id);await close(mid,req.uid);await finalize(mid);res.json({ok:true})}));
async function roster(req,mid){const m=await ref('meetings',mid).get();fail(m.exists,'NOT_FOUND','Pertemuan tidak ditemukan.',404);await classAccess(req,m.data().classId,{teacher:true});let s=await ref('attendanceSessions',mid).get();if(s.exists&&s.data().state==='open'&&s.data().closesAt?.toMillis()<=Date.now()){await close(mid);await finalize(mid);s=await ref('attendanceSessions',mid).get();}else if(s.exists&&s.data().state==='closed'&&!s.data().finalizedAt){await finalize(mid);s=await ref('attendanceSessions',mid).get();}const [parts,att]=await Promise.all([m.ref.collection('participants').get(),db.collection('attendance').where('meetingId','==',mid).get()]);const map=new Map(att.docs.map(d=>[d.data().studentId,row(d)]));return {meeting:row(m),session:publicSession(s),data:parts.docs.map(p=>({studentId:p.id,displayName:p.data().displayName,schoolClass:p.data().schoolClass,status:'belum_presensi',checkedInAt:null,...map.get(p.id)})).sort((a,b)=>a.displayName.localeCompare(b.displayName))}}
app.get('/api/meetings/:id/attendance',route(async(req,res)=>res.json(await roster(req,docId(req.params.id)))));
app.patch('/api/meetings/:id/attendance/:uid',route(async(req,res)=>{const mid=docId(req.params.id),uid=docId(req.params.uid),status=req.body.status,reason=str(req.body.reason,'Alasan',500);fail(statuses.includes(status),'INVALID_STATUS','Status tidak valid.');await db.runTransaction(async tx=>{const m=await tx.get(ref('meetings',mid));fail(m.exists,'NOT_FOUND','Pertemuan tidak ditemukan.',404);await teacherTx(tx,req.uid,m.data().classId);const aRef=ref('attendance',attendanceId(mid,uid));const [p,s,a]=await Promise.all([tx.get(m.ref.collection('participants').doc(uid)),tx.get(ref('attendanceSessions',mid)),tx.get(aRef)]);fail(p.exists&&s.exists,'NOT_ELIGIBLE','Siswa belum masuk snapshot peserta.');const old=a.exists?a.data():null;const data={meetingId:mid,classId:m.data().classId,studentId:uid,displayName:p.data().displayName,schoolClass:p.data().schoolClass,meetingTitle:m.data().title,meetingStartsAt:m.data().startsAt,status,checkedInAt:['hadir','terlambat'].includes(status)?old?.checkedInAt||null:null,source:'manual',qrVersion:old?.qrVersion||null,recordedBy:req.uid,updatedAt:now()};tx.set(aRef,data);audit(tx,req.uid,'correct_attendance','attendance',aRef.id,m.data().classId,{reason,oldValue:old?{status:old.status,source:old.source}:null,newValue:{status,source:'manual'}})});res.json({ok:true})}));
app.get('/api/me/attendance',route(async(req,res)=>{role(req,'siswa');res.json(await paginate(db.collection('attendance').where('studentId','==',req.uid).orderBy('meetingStartsAt','desc'),req,'attendance'))}));
app.get('/api/meetings/:id/export',route(async(req,res)=>{const r=await roster(req,docId(req.params.id));fail(r.session?.state==='closed'&&r.session?.finalizedAt,'NOT_FINAL','Tutup sesi dan tunggu finalisasi sebelum mengekspor rekap final.',409);res.set('Content-Type','text/csv; charset=utf-8');res.set('Content-Disposition','attachment; filename="presensi-secure.csv"');res.send(safeCSV([['Pertemuan','Tanggal','Nama','Kelas','Status','Check-in','Sumber'],...r.data.map(x=>[r.meeting.title,r.meeting.startsAt,x.displayName,x.schoolClass,x.status,x.checkedInAt||'',x.source])]))}));
let cleanupCounter=0;
async function opportunisticCleanup(){cleanupCounter++;if(cleanupCounter%50!==0)return;try{const old=await db.collection('qrTokens').where('purgeAt','<=',now()).limit(50).get();if(!old.empty){const batch=db.batch();old.docs.forEach(d=>batch.delete(d.ref));await batch.commit();}}catch(e){console.error('Opportunistic cleanup:',e.message);}}
app.use((req,res)=>res.status(404).json({code:'NOT_FOUND',message:'Endpoint tidak ditemukan.'}));
app.use((err,req,res,next)=>{if(res.headersSent)return next(err);const status=err.status||500;if(status>=500)console.error('Request failed',{method:req.method,path:req.path,errorType:err.name,code:err.code||'INTERNAL'});res.status(status).json({code:err instanceof AppError?err.code:status===413?'FILE_TOO_LARGE':'INTERNAL',message:err instanceof AppError?err.message:status===413?'Data melebihi batas ukuran.':'Terjadi kesalahan server. Coba lagi atau hubungi pengelola.'})});
export {app};
if(process.env.PORT||process.env.SERVE_PORT||(!process.env.K_SERVICE&&!process.env.FUNCTION_TARGET&&!process.env.FUNCTIONS_EMULATOR)){
  const port=Number(process.env.PORT||process.env.SERVE_PORT||8080);
  app.listen(port,'0.0.0.0',()=>console.log(`SECURE API listening on http://0.0.0.0:${port}`));
}
